# Generated by Django 5.1.2 on 2024-10-10 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('unidad_medida', models.CharField(choices=[('Unidad(u)', 'Unidad(u)'), ('Gramos(g)', 'Gramos(g)'), ('Kilogramos(kg)', 'Kilogramos(kg)'), ('Litros(L)', 'Litros(L)'), ('Mililitros(ml)', 'Mililitros(ml)')], max_length=15, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('Unidad(u)', 'Unidad(u)'), ('Gramos(g)', 'Gramos(g)'), ('Kilogramos(kg)', 'Kilogramos(kg)'), ('Litros(L)', 'Litros(L)'), ('Mililitros(ml)', 'Mililitros(ml)')], max_length=15, null=True)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platos.plato')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
