# Generated by Django 5.1.2 on 2024-10-10 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_egreso', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Consignación', 'Consignación'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque'), ('Tarjeta crédito', 'Tarjeta crédito'), ('Tarjeta débito', 'Tarjeta débito')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('impuesto', models.CharField(choices=[('Ninguno', 'Ninguno'), ('IVA Exento (0%)', 'IVA Exento (0%)'), ('IVA Excluido (0%)', 'IVA Excluido (0%)'), ('IVA (5.00%)', 'IVA (5.00%)'), ('IVA (19.00%)', 'IVA (19.00%)'), ('IVA (8.00%)', 'IVA (8.00%)')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='archivos_adjunto/')),
                ('concepto', models.CharField(choices=[('sueldos_personal_ventas', 'Sueldos personal de ventas'), ('horas_extras_recargos', 'Horas extras y recargos personal de ventas'), ('comisiones_personal_ventas', 'Comisiones personal de ventas'), ('auxilio_transporte', 'Auxilio de transporte personal de ventas'), ('cesantias_personal_ventas', 'Cesantías personal de ventas'), ('intereses_cesantias', 'Intereses sobre cesantías personal de ventas'), ('prima_servicios', 'Prima de servicios personal de ventas'), ('vacaciones_personal_ventas', 'Vacaciones personal de ventas'), ('dotacion_trabajadores', 'Dotación a trabajadores de ventas'), ('aportes_arl', 'Aportes a ARL personal de ventas'), ('aportes_eps', 'Aportes a EPS personal de ventas'), ('aportes_fondo_pensiones_cesantias', 'Aportes fondo de pensiones y cesantías personal de ventas'), ('aportes_cajas_compensacion', 'Aportes cajas de compensación familiar personal de ventas'), ('aportes_icbf', 'Aportes ICBF personal de ventas'), ('aportes_sena', 'Aportes SENA personal de ventas'), ('gastos_administracion', 'Gastos de administración'), ('gastos_personal', 'Gastos de personal'), ('sueldos_salarios', 'Sueldos y salarios'), ('horas_extras_recargos', 'Horas extras y recargos'), ('comisiones', 'Comisiones'), ('auxilio_transporte', 'Auxilio de transporte'), ('cesantias', 'Cesantías'), ('intereses_cesantias', 'Intereses sobre cesantías'), ('prima_servicios', 'Prima de servicios'), ('vacaciones', 'Vacaciones'), ('dotacion_trabajadores', 'Dotación a trabajadores'), ('aportes_arl', 'Aportes a ARL'), ('aportes_eps', 'Aportes a EPS'), ('aportes_fondo_pensiones_cesantias', 'Aportes fondo de pensiones y cesantías'), ('aportes_cajas_compensacion', 'Aportes cajas de compensación familiar'), ('aportes_icbf', 'Aportes ICBF'), ('aportes_sena', 'Aportes SENA'), ('servicios_publicos', 'Servicios públicos'), ('gas', 'Gas'), ('aseo', 'Aseo'), ('agua', 'Agua'), ('energia_electrica', 'Energía eléctrica'), ('telefono_internet', 'Teléfono / Internet'), ('transporte_acarreo', 'Transporte y acarreo'), ('otros_servicios', 'Otros servicios'), ('propaganda_publicidad', 'Propaganda y publicidad'), ('elementos_aseo', 'Elementos de aseo y cafetería'), ('utiles_papeleria', 'Útiles, papelería y fotocopia'), ('combustibles_lubricantes', 'Combustibles y lubricantes'), ('taxis_buses', 'Taxis y buses'), ('estacionamiento', 'Estacionamiento'), ('mantenimiento_reparaciones', 'Mantenimiento y reparaciones'), ('construccion_edificacion', 'Construcción y edificación'), ('caja', 'Caja'), ('efectivo_equivalentes', 'Efectivo y equivalentes de efectivo'), ('bancos', 'Bancos'), ('inventario_mercancias', 'Inventario de mercancías'), ('propiedad_planta_equipo', 'Propiedad, planta y equipo'), ('terrenos', 'Terrenos'), ('construcciones_edificaciones', 'Construcciones y edificaciones'), ('equipo_oficina', 'Equipo de oficina'), ('muebles_enseres', 'Muebles y enseres'), ('equipo_computacion', 'Equipo de computación'), ('vehiculos', 'Vehículos'), ('depreciacion_acumulada', 'Depreciación acumulada'), ('impuestos_por_pagar', 'Impuestos por pagar'), ('impuesto_ventas_por_pagar', 'Impuesto a las ventas por pagar'), ('iva_devenido_compras', 'IVA devuelto en compras'), ('iva_devuelto_ventas', 'IVA devuelto en ventas'), ('impuesto_industria_comercio', 'Impuesto de industria y comercio por pagar'), ('retenciones_por_pagar', 'Retenciones por pagar'), ('retencion_fuente_por_pagar', 'Retención en la fuente por pagar'), ('retencion_iva_por_pagar', 'Retención de IVA por pagar'), ('otros_gastos_generales', 'Otros gastos generales'), ('otros_ingresos_diversos', 'Otros ingresos diversos')], max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
