# Generated by Django 5.1.2 on 2024-10-10 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesas', '0001_initial'),
        ('platos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Consignación', 'Consignación'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque'), ('Tarjeta crédito', 'Tarjeta crédito'), ('Tarjeta débito', 'Tarjeta débito')], max_length=20)),
                ('cedula_cliente', models.CharField(max_length=20)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('impuesto', models.CharField(choices=[('Ninguno', 'Ninguno'), ('IVA Exento (0%)', 'IVA Exento (0%)'), ('IVA Excluido (0%)', 'IVA Excluido (0%)'), ('IVA (5.00%)', 'IVA (5.00%)'), ('IVA (19.00%)', 'IVA (19.00%)'), ('IVA (8.00%)', 'IVA (8.00%)')], default='Ninguno', max_length=20)),
                ('total_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sin_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_propina', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesas.mesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.compra')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platos.plato')),
            ],
        ),
        migrations.CreateModel(
            name='CompraDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Consignación', 'Consignación'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque'), ('Tarjeta crédito', 'Tarjeta crédito'), ('Tarjeta débito', 'Tarjeta débito')], max_length=20)),
                ('cedula_cliente', models.CharField(max_length=20)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('direccion_cliente', models.CharField(max_length=50)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('impuesto', models.CharField(choices=[('Ninguno', 'Ninguno'), ('IVA Exento (0%)', 'IVA Exento (0%)'), ('IVA Excluido (0%)', 'IVA Excluido (0%)'), ('IVA (5.00%)', 'IVA (5.00%)'), ('IVA (19.00%)', 'IVA (19.00%)'), ('IVA (8.00%)', 'IVA (8.00%)')], default='Ninguno', max_length=20)),
                ('total_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sin_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_propina', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalleDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platos.plato')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.compradomicilio')),
            ],
        ),
    ]
