# Generated by Django 5.1.2 on 2024-10-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradomicilio',
            name='direccion_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='compradomicilio',
            name='nombre_cliente',
            field=models.CharField(max_length=50),
        ),
    ]
