# Generated by Django 5.1.2 on 2024-10-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodomicilio',
            name='direccion_cliente',
            field=models.CharField(max_length=200),
        ),
    ]
