# Generated by Django 5.1.2 on 2024-10-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedidodomicilio_direccion_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodomicilio',
            name='nombre_cliente',
            field=models.CharField(max_length=100),
        ),
    ]
