# Generated by Django 5.1.2 on 2024-10-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedidodomicilio_nombre_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodomicilio',
            name='nombre_cliente',
            field=models.CharField(max_length=50),
        ),
    ]
