# Generated by Django 5.1.2 on 2024-10-10 04:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCajaInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('efectivo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efectivo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_propina', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('efectivo_final_registrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ventas_domicilios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pagos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencias', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('En Curso', 'En Curso'), ('Finalizado', 'Finalizado')], default='En Curso', max_length=20)),
                ('monedas_50', models.IntegerField(default=0)),
                ('monedas_100', models.IntegerField(default=0)),
                ('monedas_200', models.IntegerField(default=0)),
                ('monedas_500', models.IntegerField(default=0)),
                ('monedas_1000', models.IntegerField(default=0)),
                ('billetes_2000', models.IntegerField(default=0)),
                ('billetes_5000', models.IntegerField(default=0)),
                ('billetes_10000', models.IntegerField(default=0)),
                ('billetes_20000', models.IntegerField(default=0)),
                ('billetes_50000', models.IntegerField(default=0)),
                ('billetes_100000', models.IntegerField(default=0)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_consignacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cheque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tarjeta_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tarjeta_debito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_efectivo_domicilios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_consignacion_domicilios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_transferencia_domicilios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cheque_domicilios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tarjeta_credito_domicilios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tarjeta_debito_domicilios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
