# Generated by Django 5.1.2 on 2024-10-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='es_publica',
            field=models.BooleanField(default=False),
        ),
    ]
